### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Mcbeany** [cooldogedev/libPromise#5]
```
Fatal error: Uncaught Error: Class "cooldogedev\libPromise\constant\PromiseState" not found in D:\PocketMine-MP\virions\libPromise\src\cooldogedev\libPromise\thread\ThreadedPromise.php:87
Stack trace:
#0 D:\PocketMine-MP\virions\libPromise\src\cooldogedev\libPromise\traits\SharedPromisePartsTrait.php(73): cooldogedev\libPromise\thread\ThreadedPromise->handleRejection()
#1 D:\PocketMine-MP\virions\libPromise\src\cooldogedev\libPromise\thread\PromiseSettlerThread.php(73): cooldogedev\libPromise\thread\ThreadedPromise->settle()
#2 phar://D:/PocketMine-MP/PocketMine-MP.phar/src/thread/CommonThreadPartsTrait.php(93): cooldogedev\libPromise\thread\PromiseSettlerThread->onRun()
#3 [internal function]: pocketmine\thread\Thread->run()
#4 {main}
  thrown in D:\PocketMine-MP\virions\libPromise\src\cooldogedev\libPromise\thread\ThreadedPromise.php on line 87
```
there is no other thread running and i haven't changed anything

**Comment by cooldogedev** [comment]
That's a very strange error, can you provide the steps to reproduce it with a fresh server? +

**Comment by Mcbeany** [comment]
I tried creating a new server (latest binary and PocketMine-MP version) and re-downloading your virion but the error still occurs
![image](https://user-images.githubusercontent.com/77101686/148142948-fef6b23f-ca00-4276-9c8d-a7443ddc276f.png)

**Comment by cooldogedev** [comment]
Sorry for the late reply, I'm currently busy with school. It clearly says the class wasn't found it could be a corrupted installation?

**Comment by cooldogedev** [comment]
I'll try to reproduce this as soon as possible

**Comment by Mcbeany** [comment]
This bug no longer appears after the latest commit
